
import React from 'react';
import { useLocalization } from '../hooks/useLocalization';
import { X, Copy, Database, Image as ImageIcon, Users, AlertTriangle, ShieldAlert, CheckCircle, Unlock, Bell, ShoppingBag, ListPlus, UserCheck, Megaphone, ShieldCheck, Layers, Zap, Tag, FileText, MessageSquare, ThumbsUp, BrainCircuit } from 'lucide-react';

const CodeBlock: React.FC<{ title: string; code: string }> = ({ title, code }) => {
  const { t } = useLocalization();
  const [copied, setCopied] = React.useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="mb-6">
      <h4 className="text-lg font-semibold text-dark dark:text-light mb-2">{title}</h4>
      <div className="relative bg-gray-200 dark:bg-gray-900 rounded-lg p-4 font-mono text-sm text-gray-800 dark:text-gray-300 overflow-x-auto">
        <button
          onClick={handleCopy}
          className="absolute top-2 right-2 p-1.5 bg-gray-300 dark:bg-gray-700 rounded-md hover:bg-gray-400 dark:hover:bg-gray-600"
          aria-label={t('copyCode')}
        >
          <Copy size={16} />
        </button>
        <pre><code>{code}</code></pre>
        {copied && <span className="absolute bottom-2 right-2 text-xs text-green-600 dark:text-green-400">{t('copied')}</span>}
      </div>
    </div>
  );
};


const DatabaseSetup: React.FC<{ isOpen: boolean; onClose: () => void; }> = ({ isOpen, onClose }) => {
  const { t } = useLocalization();
  
  // SQL FIX FOR V29: Duplicate Scan Prevention
  const v29SQL = `-- V29: Prevent Duplicate QR Scans
-- Add appointment_id to scan_history
ALTER TABLE public.scan_history ADD COLUMN IF NOT EXISTS appointment_id bigint;

NOTIFY pgrst, 'reload config';`;

  // SQL FOR V24
  const fixV24SQL = `-- FIX V24: Add Missing Categories & Refresh Cache
ALTER TABLE public.providers ADD COLUMN IF NOT EXISTS category text DEFAULT NULL;
ALTER TABLE public.providers ADD COLUMN IF NOT EXISTS specialty text DEFAULT NULL;
ALTER TABLE public.providers ADD COLUMN IF NOT EXISTS neighborhood text DEFAULT NULL;
NOTIFY pgrst, 'reload config';`;

  // SQL FOR V25 (Dynamic Categories)
  const v25SQL = `-- V25: Dynamic Categories & Specialties Management
CREATE TABLE IF NOT EXISTS public.app_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.app_specialties (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id bigint REFERENCES public.app_categories(id) ON DELETE CASCADE,
  name text NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);
ALTER TABLE public.app_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_specialties ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Categories" ON public.app_categories FOR SELECT USING (true);
CREATE POLICY "Public Read Specialties" ON public.app_specialties FOR SELECT USING (true);
CREATE POLICY "Admin Manage Categories" ON public.app_categories FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin Manage Specialties" ON public.app_specialties FOR ALL USING (true) WITH CHECK (true);
INSERT INTO public.app_categories (name) VALUES 
('طبيب'), ('محامي'), ('محاسب'), ('صيدلية'), ('مختبر'), ('مدرسة'), 
('حرفي'), ('نقل'), ('عقارات'), ('تجميل'), ('مطعم')
ON CONFLICT (name) DO NOTHING;
NOTIFY pgrst, 'reload config';`;

  // SQL FOR V27 (Advanced Provider Ads / Stories)
  const v27SQL = `-- V27: Advanced Provider Ads (Stories) System
CREATE TABLE IF NOT EXISTS public.provider_ads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id bigint REFERENCES public.providers(id) ON DELETE CASCADE,
  message text,
  image_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.ad_views (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint REFERENCES public.clients(id) ON DELETE CASCADE,
  ad_id bigint REFERENCES public.provider_ads(id) ON DELETE CASCADE,
  viewed_at timestamp with time zone DEFAULT now(),
  UNIQUE(user_id, ad_id)
);
ALTER TABLE public.provider_ads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ad_views ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Ads" ON public.provider_ads FOR SELECT USING (true);
CREATE POLICY "Provider Manage Ads" ON public.provider_ads FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Manage Views" ON public.ad_views FOR ALL USING (true) WITH CHECK (true);
NOTIFY pgrst, 'reload config';`;

  // SQL FOR V28 (Store Reviews & Orders Fix)
  const v28SQL = `-- V28: Store Reviews & Orders Table Fixes
CREATE TABLE IF NOT EXISTS public.product_reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint REFERENCES public.products(id) ON DELETE CASCADE,
  user_name text,
  comment text,
  created_at timestamp with time zone DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  user_type text,
  total_amount numeric,
  status text DEFAULT 'pending',
  items jsonb,
  customer_details jsonb,
  created_at timestamp with time zone DEFAULT now()
);
ALTER TABLE public.product_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Reviews" ON public.product_reviews FOR SELECT USING (true);
CREATE POLICY "Public Insert Reviews" ON public.product_reviews FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Manage Orders" ON public.orders FOR ALL USING (true) WITH CHECK (true);
NOTIFY pgrst, 'reload config';`;

  const completeSQL = `-- Complete SQL Script
${fixV24SQL}
${v25SQL}
${v27SQL}
${v28SQL}
${v29SQL}
`;

  if (!isOpen) return null;

  return (
    <>
      <div className="fixed inset-0 bg-black/60 z-40" onClick={onClose}></div>
      <div className="fixed top-0 right-0 rtl:left-0 rtl:right-auto h-full w-full max-w-2xl bg-gray-100 dark:bg-gray-800 shadow-xl z-50 transform transition-transform duration-300 ease-in-out" style={{ transform: isOpen ? 'translateX(0)' : 'translateX(100%)' }}>
        <div className="p-4 flex justify-between items-center border-b border-gray-200 dark:border-gray-700 sticky top-0 bg-gray-100 dark:bg-gray-800 z-10">
          <h3 className="text-xl font-bold text-dark dark:text-light flex items-center gap-2">
            <Database /> {t('databaseSetupTitle')}
          </h3>
          <button onClick={onClose} className="p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-600">
            <X size={24} className="text-dark dark:text-light" />
          </button>
        </div>
        <div className="p-6 h-[calc(100vh-65px)] overflow-y-auto">
          
          {/* V29 UPDATE BLOCK (NEW) */}
           <div className="mb-8 p-4 border-l-4 border-blue-500 bg-blue-50 dark:bg-blue-900/20 rounded-r-lg shadow-lg animate-fade-in">
             <div className="flex items-center gap-2 mb-2">
                <ShieldCheck className="text-blue-600 dark:text-blue-400" size={24}/>
                <h3 className="text-xl font-bold text-blue-600 dark:text-blue-400">
                   V29: Advanced Security (QR)
                </h3>
             </div>
             <p className="mb-3 text-sm text-gray-700 dark:text-gray-300 font-bold">
                Updates 'scan_history' to prevent duplicate scans for the same appointment.
             </p>
             <CodeBlock title="SQL V29 Code" code={v29SQL.trim()} />
          </div>

          <p className="mb-6 text-gray-700 dark:text-gray-300">{t('databaseSetupDesc')}</p>
          <CodeBlock title={t('completeSQLScript')} code={completeSQL.trim()} />
        </div>
      </div>
    </>
  );
};

export default DatabaseSetup;
