
import React from 'react';
import { useLocalization } from '../hooks/useLocalization';
import { X, Copy, Database, Image as ImageIcon, Users, AlertTriangle, ShieldAlert, CheckCircle, Unlock, Bell, ShoppingBag, ListPlus, UserCheck, Megaphone, ShieldCheck, Layers } from 'lucide-react';

const CodeBlock: React.FC<{ title: string; code: string }> = ({ title, code }) => {
  const { t } = useLocalization();
  const [copied, setCopied] = React.useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="mb-6">
      <h4 className="text-lg font-semibold text-dark dark:text-light mb-2">{title}</h4>
      <div className="relative bg-gray-200 dark:bg-gray-900 rounded-lg p-4 font-mono text-sm text-gray-800 dark:text-gray-300 overflow-x-auto">
        <button
          onClick={handleCopy}
          className="absolute top-2 right-2 p-1.5 bg-gray-300 dark:bg-gray-700 rounded-md hover:bg-gray-400 dark:hover:bg-gray-600"
          aria-label={t('copyCode')}
        >
          <Copy size={16} />
        </button>
        <pre><code>{code}</code></pre>
        {copied && <span className="absolute bottom-2 right-2 text-xs text-green-600 dark:text-green-400">{t('copied')}</span>}
      </div>
    </div>
  );
};


const DatabaseSetup: React.FC<{ isOpen: boolean; onClose: () => void; }> = ({ isOpen, onClose }) => {
  const { t } = useLocalization();
  
  // ... existing variables ...
  const clientsTableSQL = `CREATE TABLE IF NOT EXISTS public.clients (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  full_name text NULL,
  phone text NULL,
  password text NULL,
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_phone_key UNIQUE (phone)
) TABLESPACE pg_default;`;

  const providersTableSQL = `CREATE TABLE IF NOT EXISTS public.providers (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NULL,
  service_type text NULL,
  location text NULL,
  username text NULL,
  password text NULL,
  phone text NULL,
  is_active boolean DEFAULT false,
  subscription_end_date timestamp with time zone NULL,
  latitude float NULL,
  longitude float NULL,
  bio text NULL,
  profile_image_url text NULL,
  CONSTRAINT providers_pkey PRIMARY KEY (id),
  CONSTRAINT providers_username_key UNIQUE (username)
) TABLESPACE pg_default;`;

  const appointmentsTableSQL = `CREATE TABLE IF NOT EXISTS public.appointments (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  client_id bigint NULL,
  provider_id bigint NULL,
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT appointments_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT appointments_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE
) TABLESPACE pg_default;`;

  const followUpsTableSQL = `CREATE TABLE IF NOT EXISTS public.follow_ups (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  client_id bigint NULL,
  provider_id bigint NULL,
  next_appointment_date timestamp with time zone NULL,
  notes text NULL,
  medication_image_url text NULL,
  CONSTRAINT follow_ups_pkey PRIMARY KEY (id),
  CONSTRAINT follow_ups_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT follow_ups_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE
) TABLESPACE pg_default;`;

  const announcementsTableSQL = `CREATE TABLE IF NOT EXISTS public.announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  provider_id bigint NULL,
  message text NULL,
  CONSTRAINT announcements_pkey PRIMARY KEY (id),
  CONSTRAINT announcements_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE
) TABLESPACE pg_default;`;

  const followsTableSQL = `CREATE TABLE IF NOT EXISTS public.follows (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  client_id bigint NULL,
  provider_id bigint NULL,
  CONSTRAINT follows_pkey PRIMARY KEY (id),
  CONSTRAINT follows_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT follows_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE,
  CONSTRAINT follows_unique UNIQUE (client_id, provider_id)
) TABLESPACE pg_default;`;

  const scanHistoryTableSQL = `CREATE TABLE IF NOT EXISTS public.scan_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  provider_id bigint NULL,
  client_name text NULL,
  client_phone text NULL,
  CONSTRAINT scan_history_pkey PRIMARY KEY (id),
  CONSTRAINT scan_history_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE
) TABLESPACE pg_default;`;

const providerServicesTableSQL = `CREATE TABLE IF NOT EXISTS public.provider_services (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  provider_id bigint NULL,
  name text NOT NULL,
  price numeric NULL,
  discount_price numeric NULL,
  CONSTRAINT provider_services_pkey PRIMARY KEY (id),
  CONSTRAINT provider_services_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE
) TABLESPACE pg_default;`;

const v9UpdateSQL = `-- Update V9: Public Storage Access
INSERT INTO storage.buckets (id, name, public) VALUES ('profiles', 'profiles', true) ON CONFLICT (id) DO UPDATE SET public = true;
DROP POLICY IF EXISTS "Authenticated Upload Profiles" ON storage.objects;
DROP POLICY IF EXISTS "Public Access Profiles" ON storage.objects;
CREATE POLICY "Public Access Profiles" ON storage.objects FOR ALL USING (bucket_id = 'profiles');
NOTIFY pgrst, 'reload config';`;

const v10UpdateSQL = `-- Update V10: Provider Notifications System
CREATE TABLE IF NOT EXISTS public.provider_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  provider_id bigint NULL,
  message text NULL,
  is_read boolean DEFAULT false,
  type text DEFAULT 'BOOKING',
  CONSTRAINT provider_notifications_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;
ALTER TABLE public.provider_notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access ProviderNotifications" ON public.provider_notifications FOR ALL USING (true) WITH CHECK (true);
NOTIFY pgrst, 'reload config';`;

const v11UpdateSQL = `-- Update V11: Products and Orders
CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  description text NULL,
  price numeric NOT NULL,
  image_url text NULL,
  category text DEFAULT 'General',
  CONSTRAINT products_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id bigint NOT NULL,
  user_type text NOT NULL,
  total_amount numeric NOT NULL,
  status text DEFAULT 'pending',
  items jsonb NULL,
  CONSTRAINT orders_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Products" ON public.products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Orders" ON public.orders FOR ALL USING (true) WITH CHECK (true);
NOTIFY pgrst, 'reload config';`;

const v12UpdateSQL = `-- Update V12: Advanced Store Management
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS sizes text[] DEFAULT '{}';
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS customer_details jsonb NULL;
NOTIFY pgrst, 'reload config';`;

const v13UpdateSQL = `-- Update V13: Visual System Ads & Image Buckets

-- 1. Create System Announcements Table
CREATE TABLE IF NOT EXISTS public.system_announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  title text NOT NULL,
  message text NOT NULL,
  image_url text NOT NULL,
  is_active boolean DEFAULT true,
  CONSTRAINT system_announcements_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- 2. Enable RLS and Policies for System Ads
ALTER TABLE public.system_announcements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access SystemAds" ON public.system_announcements FOR ALL USING (true) WITH CHECK (true);

-- 3. Create Storage Buckets for Products and Ads
INSERT INTO storage.buckets (id, name, public) VALUES ('product-images', 'product-images', true) ON CONFLICT (id) DO UPDATE SET public = true;
INSERT INTO storage.buckets (id, name, public) VALUES ('announcement-images', 'announcement-images', true) ON CONFLICT (id) DO UPDATE SET public = true;

-- 4. Set Public Policies for Buckets (Allow anyone to read/upload for demo simplicity)
CREATE POLICY "Public Access ProductImages" ON storage.objects FOR ALL USING (bucket_id = 'product-images');
CREATE POLICY "Public Access AdImages" ON storage.objects FOR ALL USING (bucket_id = 'announcement-images');

NOTIFY pgrst, 'reload config';`;

const v14UpdateSQL = `-- Update V14: FIX PERMISSIONS (Edit Products & Save Orders)

-- 1. Reset permissions for Products to allow Admin edits/deletes
DROP POLICY IF EXISTS "Public Access Products" ON public.products;
CREATE POLICY "Public Access Products" ON public.products FOR ALL USING (true) WITH CHECK (true);

-- 2. Reset permissions for Orders to allow Users to create orders
DROP POLICY IF EXISTS "Public Access Orders" ON public.orders;
CREATE POLICY "Public Access Orders" ON public.orders FOR ALL USING (true) WITH CHECK (true);

NOTIFY pgrst, 'reload config';`;

const v15UpdateSQL = `-- Update V15: Support Multiple Images in Ads
ALTER TABLE public.system_announcements ADD COLUMN IF NOT EXISTS images text[];
NOTIFY pgrst, 'reload config';`;

const createAdminSQL = `-- Create Admin User
INSERT INTO public.providers (
  name, service_type, location, username, password, phone, is_active, subscription_end_date
)
SELECT 'Store Admin', 'Administration', 'Tangier', 'admin', '123456', '0617774846', true, NOW() + INTERVAL '365 days'
WHERE NOT EXISTS (
    SELECT 1 FROM public.providers WHERE username = 'admin'
);`;

const completeSQL = `-- Complete SQL Script
${clientsTableSQL}
${providersTableSQL}
${appointmentsTableSQL}
${followUpsTableSQL}
${announcementsTableSQL}
${followsTableSQL}
${scanHistoryTableSQL}
${providerServicesTableSQL}

-- New Tables
CREATE TABLE IF NOT EXISTS public.system_announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  title text NOT NULL,
  message text NOT NULL,
  image_url text NOT NULL,
  is_active boolean DEFAULT true,
  images text[] DEFAULT NULL,
  CONSTRAINT system_announcements_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Buckets (manual step usually, but tried here)
INSERT INTO storage.buckets (id, name, public) VALUES ('profiles', 'profiles', true) ON CONFLICT (id) DO UPDATE SET public = true;
INSERT INTO storage.buckets (id, name, public) VALUES ('product-images', 'product-images', true) ON CONFLICT (id) DO UPDATE SET public = true;
INSERT INTO storage.buckets (id, name, public) VALUES ('announcement-images', 'announcement-images', true) ON CONFLICT (id) DO UPDATE SET public = true;
`;

  if (!isOpen) return null;

  return (
    <>
      <div className="fixed inset-0 bg-black/60 z-40" onClick={onClose}></div>
      <div className="fixed top-0 right-0 rtl:left-0 rtl:right-auto h-full w-full max-w-2xl bg-gray-100 dark:bg-gray-800 shadow-xl z-50 transform transition-transform duration-300 ease-in-out" style={{ transform: isOpen ? 'translateX(0)' : 'translateX(100%)' }}>
        <div className="p-4 flex justify-between items-center border-b border-gray-200 dark:border-gray-700 sticky top-0 bg-gray-100 dark:bg-gray-800 z-10">
          <h3 className="text-xl font-bold text-dark dark:text-light flex items-center gap-2">
            <Database /> {t('databaseSetupTitle')}
          </h3>
          <button onClick={onClose} className="p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-600">
            <X size={24} className="text-dark dark:text-light" />
          </button>
        </div>
        <div className="p-6 h-[calc(100vh-65px)] overflow-y-auto">
          <p className="mb-6 text-gray-700 dark:text-gray-300">{t('databaseSetupDesc')}</p>

          {/* Create Admin Block */}
          <div className="mb-8 p-4 border-l-4 border-green-500 bg-green-50 dark:bg-green-900/20 rounded-r-lg shadow-lg animate-fade-in">
             <h3 className="text-xl font-bold text-green-600 dark:text-green-400 flex items-center gap-2 mb-4">
                <UserCheck /> {t('createAdminUser')}
             </h3>
             <CodeBlock title={t('createAdminUser')} code={createAdminSQL.trim()} />
          </div>

          {/* V15 Update Block */}
          <div className="mb-8 p-4 border-l-4 border-blue-500 bg-blue-50 dark:bg-blue-900/20 rounded-r-lg shadow-lg animate-fade-in">
             <h3 className="text-xl font-bold text-blue-600 dark:text-blue-400 flex items-center gap-2 mb-4">
                <Layers /> V15 Update: Multi-Image Ads
             </h3>
             <p className="mb-2 text-sm text-gray-600 dark:text-gray-400">Run this to allow multiple images in advertisements.</p>
             <CodeBlock title="V15 Multi-Image Ads" code={v15UpdateSQL.trim()} />
          </div>

          {/* V14 Update Block (Fix Permissions) */}
          <div className="mb-8 p-4 border-l-4 border-red-500 bg-red-50 dark:bg-red-900/20 rounded-r-lg shadow-lg animate-fade-in">
             <h3 className="text-xl font-bold text-red-600 dark:text-red-400 flex items-center gap-2 mb-4">
                <ShieldCheck /> V14 Update: Fix Edit/Delete & Orders
             </h3>
             <p className="mb-2 text-sm text-gray-600 dark:text-gray-400">Run this to allow Admin to edit products and Users to save orders.</p>
             <CodeBlock title="V14 Permissions Fix" code={v14UpdateSQL.trim()} />
          </div>
          
          {/* V13 Update Block */}
          <div className="mb-8 p-4 border-l-4 border-orange-500 bg-orange-50 dark:bg-orange-900/20 rounded-r-lg shadow-lg animate-fade-in">
             <h3 className="text-xl font-bold text-orange-600 dark:text-orange-400 flex items-center gap-2 mb-4">
                <Megaphone /> {t('v13UpdateTitle')}
             </h3>
             <CodeBlock title={t('v13UpdateTitle')} code={v13UpdateSQL.trim()} />
          </div>

          {/* V12 Update Block */}
          <div className="mb-8 p-4 border-l-4 border-purple-500 bg-purple-50 dark:bg-purple-900/20 rounded-r-lg shadow-lg animate-fade-in">
             <h3 className="text-xl font-bold text-purple-600 dark:text-purple-400 flex items-center gap-2 mb-4">
                <ListPlus /> {t('v12UpdateTitle')}
             </h3>
             <CodeBlock title={t('v12UpdateTitle')} code={v12UpdateSQL.trim()} />
          </div>

          <CodeBlock title={t('completeSQLScript')} code={completeSQL.trim()} />
        </div>
      </div>
    </>
  );
};

export default DatabaseSetup;