
import React from 'react';
import { useLocalization } from '../hooks/useLocalization';
import { X, Copy, Database, Image as ImageIcon, Users, AlertTriangle, ShieldAlert, CheckCircle } from 'lucide-react';

const CodeBlock: React.FC<{ title: string; code: string }> = ({ title, code }) => {
  const { t } = useLocalization();
  const [copied, setCopied] = React.useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="mb-6">
      <h4 className="text-lg font-semibold text-dark dark:text-light mb-2">{title}</h4>
      <div className="relative bg-gray-200 dark:bg-gray-900 rounded-lg p-4 font-mono text-sm text-gray-800 dark:text-gray-300 overflow-x-auto">
        <button
          onClick={handleCopy}
          className="absolute top-2 right-2 p-1.5 bg-gray-300 dark:bg-gray-700 rounded-md hover:bg-gray-400 dark:hover:bg-gray-600"
          aria-label={t('copyCode')}
        >
          <Copy size={16} />
        </button>
        <pre><code>{code}</code></pre>
        {copied && <span className="absolute bottom-2 right-2 text-xs text-green-600 dark:text-green-400">{t('copied')}</span>}
      </div>
    </div>
  );
};


const DatabaseSetup: React.FC<{ isOpen: boolean; onClose: () => void; }> = ({ isOpen, onClose }) => {
  const { t } = useLocalization();
  
  const clientsTableSQL = `CREATE TABLE IF NOT EXISTS public.clients (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  full_name text NULL,
  phone text NULL,
  password text NULL,
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_phone_key UNIQUE (phone)
) TABLESPACE pg_default;`;

  const providersTableSQL = `CREATE TABLE IF NOT EXISTS public.providers (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NULL,
  service_type text NULL,
  location text NULL,
  username text NULL,
  password text NULL,
  phone text NULL,
  is_active boolean DEFAULT false,
  subscription_end_date timestamp with time zone NULL,
  CONSTRAINT providers_pkey PRIMARY KEY (id),
  CONSTRAINT providers_username_key UNIQUE (username)
) TABLESPACE pg_default;`;

  const appointmentsTableSQL = `CREATE TABLE IF NOT EXISTS public.appointments (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  client_id bigint NULL,
  provider_id bigint NULL,
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT appointments_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT appointments_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE
) TABLESPACE pg_default;`;

  const followUpsTableSQL = `CREATE TABLE IF NOT EXISTS public.follow_ups (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  client_id bigint NULL,
  provider_id bigint NULL,
  next_appointment_date timestamp with time zone NULL,
  notes text NULL,
  medication_image_url text NULL,
  CONSTRAINT follow_ups_pkey PRIMARY KEY (id),
  CONSTRAINT follow_ups_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT follow_ups_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE
) TABLESPACE pg_default;`;

  const announcementsTableSQL = `CREATE TABLE IF NOT EXISTS public.announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  provider_id bigint NULL,
  message text NULL,
  CONSTRAINT announcements_pkey PRIMARY KEY (id),
  CONSTRAINT announcements_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE
) TABLESPACE pg_default;`;

const completeSQL = `-- 1. Clients Table: Stores user information
${clientsTableSQL}

-- 2. Providers Table: Stores service provider information
${providersTableSQL}

-- 3. Appointments Table: Links clients and providers for bookings
${appointmentsTableSQL}

-- 4. Follow-ups Table: For tracking medical or other follow-ups
${followUpsTableSQL}

-- 5. Announcements Table: For providers to send messages to clients
${announcementsTableSQL}`;

const sampleDataSQL = `-- Sample Data for Providers (add some examples to test the app)
-- NOTE: is_active is set to true for sample providers
INSERT INTO public.providers (name, service_type, location, username, password, phone, is_active, subscription_end_date) VALUES
('Dr. Fatima Alami', 'General Doctor', 'Ibn Batouta Clinic, Tangier', 'fatima.alami', 'pass123', '0611223344', true, now() + interval '30 days'),
('Yassine Electric', 'Electrician', 'Mesnana, Tangier', 'yassine.electric', 'pass123', '0655667788', true, now() + interval '30 days'),
('Plomberie Express', 'Plumber', 'City Center, Tangier', 'plomberie.express', 'pass123', '0699887766', true, now() + interval '30 days'),
('Dr. Karim Bennani', 'Dentist', 'Malabata, Tangier', 'karim.bennani', 'pass123', '0644332211', true, now() + interval '30 days')
ON CONFLICT (username) DO NOTHING;

-- Sample Data for Clients (for testing)
INSERT INTO public.clients (full_name, phone, password) VALUES
('Ahmed Tazi', '0600000001', 'client123'),
('Salma Alaoui', '0600000002', 'client123')
ON CONFLICT (phone) DO NOTHING;`;

const reloadSchemaSQL = `NOTIFY pgrst, 'reload config';`;

const fixPasswordSQL = `ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS password text;
ALTER TABLE public.providers ADD COLUMN IF NOT EXISTS password text;
NOTIFY pgrst, 'reload config';`;

const fixUsernameSQL = `ALTER TABLE public.providers ADD COLUMN IF NOT EXISTS username text;
NOTIFY pgrst, 'reload config';`;

const fixProviderColumnsSQL = `ALTER TABLE public.providers ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE public.providers ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT false;
ALTER TABLE public.providers ADD COLUMN IF NOT EXISTS subscription_end_date timestamp with time zone;
NOTIFY pgrst, 'reload config';`;

const activateProviderSQL = `-- Replace 'username_here' with the actual username of the provider
UPDATE public.providers
SET 
  is_active = true,
  subscription_end_date = now() + interval '30 days'
WHERE username = 'username_here';`;

const fixRLSPoliciesSQL = `-- Enable RLS
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.providers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.follow_ups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

-- DROP EXISTING POLICIES TO AVOID CONFLICTS
DROP POLICY IF EXISTS "Public Access Clients" ON public.clients;
DROP POLICY IF EXISTS "Public Access Providers" ON public.providers;
DROP POLICY IF EXISTS "Public Access Appointments" ON public.appointments;
DROP POLICY IF EXISTS "Public Access FollowUps" ON public.follow_ups;
DROP POLICY IF EXISTS "Public Access Announcements" ON public.announcements;

-- CREATE PERMISSIVE POLICIES (For development use)
CREATE POLICY "Public Access Clients" ON public.clients FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Providers" ON public.providers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Appointments" ON public.appointments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access FollowUps" ON public.follow_ups FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Announcements" ON public.announcements FOR ALL USING (true) WITH CHECK (true);

-- Reload config to ensure changes take effect
NOTIFY pgrst, 'reload config';`;

  if (!isOpen) return null;

  return (
    <>
      <div className="fixed inset-0 bg-black/60 z-40" onClick={onClose}></div>
      <div className="fixed top-0 right-0 rtl:left-0 rtl:right-auto h-full w-full max-w-2xl bg-gray-100 dark:bg-gray-800 shadow-xl z-50 transform transition-transform duration-300 ease-in-out" style={{ transform: isOpen ? 'translateX(0)' : 'translateX(100%)' }}>
        <div className="p-4 flex justify-between items-center border-b border-gray-200 dark:border-gray-700 sticky top-0 bg-gray-100 dark:bg-gray-800 z-10">
          <h3 className="text-xl font-bold text-dark dark:text-light flex items-center gap-2">
            <Database /> {t('databaseSetupTitle')}
          </h3>
          <button onClick={onClose} className="p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-600">
            <X size={24} className="text-dark dark:text-light" />
          </button>
        </div>
        <div className="p-6 h-[calc(100vh-65px)] overflow-y-auto">
          <p className="mb-6 text-gray-700 dark:text-gray-300">{t('databaseSetupDesc')}</p>
          
          <div className="mb-8 p-4 border-l-4 border-red-500 bg-red-50 dark:bg-red-900/20 rounded-r-lg">
             <h3 className="text-xl font-bold text-red-600 dark:text-red-400 flex items-center gap-2 mb-4">
                <AlertTriangle /> {t('troubleshootingTitle')}
             </h3>
             <p className="mb-4 text-gray-800 dark:text-gray-200 font-semibold">{t('troubleshootingDesc')}</p>
             <ol className="list-decimal list-inside space-y-2 text-gray-700 dark:text-gray-300">
                <li>{t('troubleshootingStep1')}</li>
                <li>{t('troubleshootingStep2')}</li>
             </ol>
             
             <div className="mt-4 pt-4 border-t border-red-200 dark:border-red-800">
                <h4 className="font-bold text-red-600 dark:text-red-400 mb-2">{t('reloadSchemaViaSQLTitle')}</h4>
                <p className="mb-2 text-gray-800 dark:text-gray-200 text-sm">{t('reloadSchemaViaSQLDesc')}</p>
                <div className="relative bg-gray-800 rounded-md p-3 font-mono text-xs text-green-400">
                    <pre>{reloadSchemaSQL}</pre>
                    <button 
                        onClick={() => {navigator.clipboard.writeText(reloadSchemaSQL)}}
                        className="absolute top-2 right-2 text-gray-400 hover:text-white"
                        title={t('copyCode')}
                    >
                        <Copy size={14} />
                    </button>
                </div>
             </div>

             <div className="mt-4 pt-4 border-t border-red-200 dark:border-red-800">
                <h4 className="font-bold text-red-600 dark:text-red-400 mb-2 flex items-center gap-2">
                  <CheckCircle size={16} />
                  {t('howToActivateProviderTitle')}
                </h4>
                <p className="mb-2 text-gray-800 dark:text-gray-200 text-sm">{t('howToActivateProviderDesc')}</p>
                <div className="relative bg-gray-800 rounded-md p-3 font-mono text-xs text-green-300">
                    <pre>{activateProviderSQL}</pre>
                    <button 
                        onClick={() => {navigator.clipboard.writeText(activateProviderSQL)}}
                        className="absolute top-2 right-2 text-gray-400 hover:text-white"
                        title={t('copyCode')}
                    >
                        <Copy size={14} />
                    </button>
                </div>
             </div>

             <div className="mt-4 pt-4 border-t border-red-200 dark:border-red-800">
                <h4 className="font-bold text-red-600 dark:text-red-400 mb-2">{t('fixMissingPasswordTitle')}</h4>
                <p className="mb-2 text-gray-800 dark:text-gray-200 text-sm">{t('fixMissingPasswordDesc')}</p>
                <div className="relative bg-gray-800 rounded-md p-3 font-mono text-xs text-yellow-400">
                    <pre>{fixPasswordSQL}</pre>
                    <button 
                        onClick={() => {navigator.clipboard.writeText(fixPasswordSQL)}}
                        className="absolute top-2 right-2 text-gray-400 hover:text-white"
                        title={t('copyCode')}
                    >
                        <Copy size={14} />
                    </button>
                </div>
             </div>

             <div className="mt-4 pt-4 border-t border-red-200 dark:border-red-800">
                <h4 className="font-bold text-red-600 dark:text-red-400 mb-2">{t('fixMissingUsernameTitle')}</h4>
                <p className="mb-2 text-gray-800 dark:text-gray-200 text-sm">{t('fixMissingUsernameDesc')}</p>
                <div className="relative bg-gray-800 rounded-md p-3 font-mono text-xs text-yellow-400">
                    <pre>{fixUsernameSQL}</pre>
                    <button 
                        onClick={() => {navigator.clipboard.writeText(fixUsernameSQL)}}
                        className="absolute top-2 right-2 text-gray-400 hover:text-white"
                        title={t('copyCode')}
                    >
                        <Copy size={14} />
                    </button>
                </div>
             </div>

              <div className="mt-4 pt-4 border-t border-red-200 dark:border-red-800">
                <h4 className="font-bold text-red-600 dark:text-red-400 mb-2">{t('fixProviderColumnsTitle')}</h4>
                <p className="mb-2 text-gray-800 dark:text-gray-200 text-sm">{t('fixProviderColumnsDesc')}</p>
                <div className="relative bg-gray-800 rounded-md p-3 font-mono text-xs text-purple-400">
                    <pre>{fixProviderColumnsSQL}</pre>
                    <button 
                        onClick={() => {navigator.clipboard.writeText(fixProviderColumnsSQL)}}
                        className="absolute top-2 right-2 text-gray-400 hover:text-white"
                        title={t('copyCode')}
                    >
                        <Copy size={14} />
                    </button>
                </div>
             </div>

             <div className="mt-4 pt-4 border-t border-red-200 dark:border-red-800">
                <h4 className="font-bold text-red-600 dark:text-red-400 mb-2 flex items-center gap-2">
                   <ShieldAlert size={16} /> {t('fixRLSTitle')}
                </h4>
                <p className="mb-2 text-gray-800 dark:text-gray-200 text-sm">{t('fixRLSDesc')}</p>
                <div className="relative bg-gray-800 rounded-md p-3 font-mono text-xs text-blue-400">
                    <pre>{fixRLSPoliciesSQL}</pre>
                    <button 
                        onClick={() => {navigator.clipboard.writeText(fixRLSPoliciesSQL)}}
                        className="absolute top-2 right-2 text-gray-400 hover:text-white"
                        title={t('copyCode')}
                    >
                        <Copy size={14} />
                    </button>
                </div>
             </div>
          </div>

          <CodeBlock title={t('completeSQLScript')} code={completeSQL.trim()} />
          
          <div className="mt-8 pt-6 border-t border-gray-300 dark:border-gray-600">
             <h3 className="text-xl font-bold text-dark dark:text-light flex items-center gap-2 mb-4">
                <Users /> {t('sampleDataTitle')}
             </h3>
             <p className="mb-4 text-gray-700 dark:text-gray-300">{t('sampleDataDesc')}</p>
             <CodeBlock title={t('sampleProviders')} code={sampleDataSQL} />
          </div>

           <div className="mt-8 pt-6 border-t border-gray-300 dark:border-gray-600">
             <h4 className="font-bold text-lg text-dark dark:text-light mb-4">{t('individualTablesTitle')}</h4>
             <CodeBlock title={t('clientsTable')} code={clientsTableSQL} />
             <CodeBlock title={t('providersTable')} code={providersTableSQL} />
             <CodeBlock title={t('appointmentsTable')} code={appointmentsTableSQL} />
             <CodeBlock title={t('followUpsTable')} code={followUpsTableSQL} />
             <CodeBlock title={t('announcementsTable')} code={announcementsTableSQL} />
          </div>

          <div className="mt-8 pt-6 border-t border-gray-300 dark:border-gray-600">
             <h3 className="text-xl font-bold text-dark dark:text-light flex items-center gap-2 mb-4">
                <ImageIcon /> {t('storageSetupTitle')}
             </h3>
             <p className="mb-4 text-gray-700 dark:text-gray-300">{t('storageSetupDesc')}</p>
             <ol className="list-decimal list-inside space-y-2 text-gray-700 dark:text-gray-300">
                <li>{t('storageStep1')}</li>
                <li>{t('storageStep2')}</li>
                <li>{t('storageStep3')}</li>
             </ol>
          </div>

        </div>
      </div>
    </>
  );
};

export default DatabaseSetup;
