
import React from 'react';
import { useLocalization } from '../hooks/useLocalization';
import { X, Copy, Database, Image as ImageIcon, Users, AlertTriangle, ShieldAlert, CheckCircle, Unlock, Bell } from 'lucide-react';

const CodeBlock: React.FC<{ title: string; code: string }> = ({ title, code }) => {
  const { t } = useLocalization();
  const [copied, setCopied] = React.useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="mb-6">
      <h4 className="text-lg font-semibold text-dark dark:text-light mb-2">{title}</h4>
      <div className="relative bg-gray-200 dark:bg-gray-900 rounded-lg p-4 font-mono text-sm text-gray-800 dark:text-gray-300 overflow-x-auto">
        <button
          onClick={handleCopy}
          className="absolute top-2 right-2 p-1.5 bg-gray-300 dark:bg-gray-700 rounded-md hover:bg-gray-400 dark:hover:bg-gray-600"
          aria-label={t('copyCode')}
        >
          <Copy size={16} />
        </button>
        <pre><code>{code}</code></pre>
        {copied && <span className="absolute bottom-2 right-2 text-xs text-green-600 dark:text-green-400">{t('copied')}</span>}
      </div>
    </div>
  );
};


const DatabaseSetup: React.FC<{ isOpen: boolean; onClose: () => void; }> = ({ isOpen, onClose }) => {
  const { t } = useLocalization();
  
  const clientsTableSQL = `CREATE TABLE IF NOT EXISTS public.clients (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  full_name text NULL,
  phone text NULL,
  password text NULL,
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_phone_key UNIQUE (phone)
) TABLESPACE pg_default;`;

  const providersTableSQL = `CREATE TABLE IF NOT EXISTS public.providers (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NULL,
  service_type text NULL,
  location text NULL,
  username text NULL,
  password text NULL,
  phone text NULL,
  is_active boolean DEFAULT false,
  subscription_end_date timestamp with time zone NULL,
  latitude float NULL,
  longitude float NULL,
  bio text NULL,
  profile_image_url text NULL,
  CONSTRAINT providers_pkey PRIMARY KEY (id),
  CONSTRAINT providers_username_key UNIQUE (username)
) TABLESPACE pg_default;`;

  const appointmentsTableSQL = `CREATE TABLE IF NOT EXISTS public.appointments (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  client_id bigint NULL,
  provider_id bigint NULL,
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT appointments_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT appointments_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE
) TABLESPACE pg_default;`;

  const followUpsTableSQL = `CREATE TABLE IF NOT EXISTS public.follow_ups (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  client_id bigint NULL,
  provider_id bigint NULL,
  next_appointment_date timestamp with time zone NULL,
  notes text NULL,
  medication_image_url text NULL,
  CONSTRAINT follow_ups_pkey PRIMARY KEY (id),
  CONSTRAINT follow_ups_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT follow_ups_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE
) TABLESPACE pg_default;`;

  const announcementsTableSQL = `CREATE TABLE IF NOT EXISTS public.announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  provider_id bigint NULL,
  message text NULL,
  CONSTRAINT announcements_pkey PRIMARY KEY (id),
  CONSTRAINT announcements_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE
) TABLESPACE pg_default;`;

  const followsTableSQL = `CREATE TABLE IF NOT EXISTS public.follows (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  client_id bigint NULL,
  provider_id bigint NULL,
  CONSTRAINT follows_pkey PRIMARY KEY (id),
  CONSTRAINT follows_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT follows_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE,
  CONSTRAINT follows_unique UNIQUE (client_id, provider_id)
) TABLESPACE pg_default;`;

  const scanHistoryTableSQL = `CREATE TABLE IF NOT EXISTS public.scan_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  provider_id bigint NULL,
  client_name text NULL,
  client_phone text NULL,
  CONSTRAINT scan_history_pkey PRIMARY KEY (id),
  CONSTRAINT scan_history_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE
) TABLESPACE pg_default;`;

const providerServicesTableSQL = `CREATE TABLE IF NOT EXISTS public.provider_services (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  provider_id bigint NULL,
  name text NOT NULL,
  price numeric NULL,
  discount_price numeric NULL,
  CONSTRAINT provider_services_pkey PRIMARY KEY (id),
  CONSTRAINT provider_services_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE
) TABLESPACE pg_default;`;

const completeSQL = `-- 1. Clients
${clientsTableSQL}
-- 2. Providers
${providersTableSQL}
-- 3. Appointments
${appointmentsTableSQL}
-- 4. Follow-ups
${followUpsTableSQL}
-- 5. Announcements
${announcementsTableSQL}
-- 6. Follows
${followsTableSQL}
-- 7. Scan History
${scanHistoryTableSQL}
-- 8. Provider Services
${providerServicesTableSQL}`;

const v2UpdateSQL = `-- Create new tables for V2
CREATE TABLE IF NOT EXISTS public.follows (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  client_id bigint NULL,
  provider_id bigint NULL,
  CONSTRAINT follows_pkey PRIMARY KEY (id),
  CONSTRAINT follows_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT follows_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE,
  CONSTRAINT follows_unique UNIQUE (client_id, provider_id)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.scan_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  provider_id bigint NULL,
  client_name text NULL,
  client_phone text NULL,
  CONSTRAINT scan_history_pkey PRIMARY KEY (id),
  CONSTRAINT scan_history_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- Ensure Providers have new columns
ALTER TABLE public.providers ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE public.providers ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT false;
ALTER TABLE public.providers ADD COLUMN IF NOT EXISTS subscription_end_date timestamp with time zone;

-- Enable RLS on new tables
ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scan_history ENABLE ROW LEVEL SECURITY;

-- Create Policies for new tables
CREATE POLICY "Public Access Follows" ON public.follows FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access ScanHistory" ON public.scan_history FOR ALL USING (true) WITH CHECK (true);

-- Refresh Cache
NOTIFY pgrst, 'reload config';`;

const v3UpdateSQL = `-- Update V3: Geolocation & Advanced Profile
-- 1. Add GPS and Bio columns to providers
ALTER TABLE public.providers ADD COLUMN IF NOT EXISTS latitude float NULL;
ALTER TABLE public.providers ADD COLUMN IF NOT EXISTS longitude float NULL;
ALTER TABLE public.providers ADD COLUMN IF NOT EXISTS bio text NULL;
ALTER TABLE public.providers ADD COLUMN IF NOT EXISTS profile_image_url text NULL;

-- 2. Create Services table
CREATE TABLE IF NOT EXISTS public.provider_services (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  provider_id bigint NULL,
  name text NOT NULL,
  price numeric NULL,
  discount_price numeric NULL,
  CONSTRAINT provider_services_pkey PRIMARY KEY (id),
  CONSTRAINT provider_services_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- 3. Enable RLS and Policies for Services
ALTER TABLE public.provider_services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access ProviderServices" ON public.provider_services FOR ALL USING (true) WITH CHECK (true);

-- 4. Refresh Cache
NOTIFY pgrst, 'reload config';`;

const v5UpdateSQL = `-- Update V5: Enhanced Search & Notifications
-- 1. Ensure public access to provider services for search
DROP POLICY IF EXISTS "Public Access ProviderServices" ON public.provider_services;
CREATE POLICY "Public Access ProviderServices" ON public.provider_services FOR SELECT USING (true);
CREATE POLICY "Provider Manage Services" ON public.provider_services FOR ALL USING (auth.uid() IS NULL); -- Allow basic CRUD for demo

-- 2. Performance Index for Search
CREATE INDEX IF NOT EXISTS providers_name_idx ON public.providers USING btree (name);
CREATE INDEX IF NOT EXISTS provider_services_name_idx ON public.provider_services USING btree (name);

-- 3. Refresh Cache
NOTIFY pgrst, 'reload config';`;

const v6UpdateSQL = `-- Update V6: Storage & GPS Fixes
-- 1. Create 'profiles' storage bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('profiles', 'profiles', true)
ON CONFLICT (id) DO NOTHING;

-- 2. Create 'medication-images' bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('medication-images', 'medication-images', true)
ON CONFLICT (id) DO NOTHING;

-- 3. Allow public access to 'profiles' bucket
DROP POLICY IF EXISTS "Public Access Profiles" ON storage.objects;
CREATE POLICY "Public Access Profiles" ON storage.objects FOR SELECT USING (bucket_id = 'profiles');

-- 4. Allow authenticated users to upload to 'profiles'
DROP POLICY IF EXISTS "Authenticated Upload Profiles" ON storage.objects;
CREATE POLICY "Authenticated Upload Profiles" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'profiles' AND auth.role() = 'authenticated');

-- 5. Allow users to update their own images (simplified for demo: allow all auth users)
DROP POLICY IF EXISTS "Authenticated Update Profiles" ON storage.objects;
CREATE POLICY "Authenticated Update Profiles" ON storage.objects FOR UPDATE USING (bucket_id = 'profiles' AND auth.role() = 'authenticated');

-- 6. Ensure profile_image_url column exists
ALTER TABLE public.providers ADD COLUMN IF NOT EXISTS profile_image_url text NULL;

-- 7. Refresh Cache
NOTIFY pgrst, 'reload config';`;

const v7UpdateSQL = `-- Update V7: Force Fix Storage
-- 1. Create/Update 'profiles' bucket to be PUBLIC
INSERT INTO storage.buckets (id, name, public)
VALUES ('profiles', 'profiles', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- 2. Ensure Provider Table has column
ALTER TABLE public.providers ADD COLUMN IF NOT EXISTS profile_image_url text NULL;

-- 3. RESET Policies (Force Delete old ones to avoid conflicts)
DROP POLICY IF EXISTS "Public Access Profiles" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Upload Profiles" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Update Profiles" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Delete Profiles" ON storage.objects;
DROP POLICY IF EXISTS "Give me access" ON storage.objects;

-- 4. CREATE Permissive Policies for Demo/App
-- Allow ANYONE to VIEW images
CREATE POLICY "Public Access Profiles" ON storage.objects FOR SELECT USING (bucket_id = 'profiles');
-- Allow authenticated users (providers) to UPLOAD
CREATE POLICY "Authenticated Upload Profiles" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'profiles' AND auth.role() = 'authenticated');
-- Allow authenticated users to UPDATE
CREATE POLICY "Authenticated Update Profiles" ON storage.objects FOR UPDATE USING (bucket_id = 'profiles' AND auth.role() = 'authenticated');

-- 5. Refresh Cache
NOTIFY pgrst, 'reload config';`;

const v8UpdateSQL = `-- Update V8: Emergency Fix for Storage Policies
-- 1. Drop ALL potential conflicting policies first (Aggressive Clean-up)
DROP POLICY IF EXISTS "Public Access Profiles" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Upload Profiles" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Update Profiles" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Delete Profiles" ON storage.objects;
DROP POLICY IF EXISTS "Give me access" ON storage.objects;
DROP POLICY IF EXISTS "Public Access" ON storage.objects;

-- 2. Ensure Bucket Exists and is Public
INSERT INTO storage.buckets (id, name, public)
VALUES ('profiles', 'profiles', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- 3. Re-Create Policies (Simpler and Permissive)
-- View: Everyone
CREATE POLICY "Public Access Profiles" ON storage.objects FOR SELECT USING (bucket_id = 'profiles');
-- Insert: Authenticated Users
CREATE POLICY "Authenticated Upload Profiles" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'profiles' AND auth.role() = 'authenticated');
-- Update: Authenticated Users
CREATE POLICY "Authenticated Update Profiles" ON storage.objects FOR UPDATE USING (bucket_id = 'profiles' AND auth.role() = 'authenticated');

NOTIFY pgrst, 'reload config';`;

const v9UpdateSQL = `-- Update V9: Public Storage Access (Fix for Custom Auth)
-- Since the app uses custom tables for auth and not Supabase Auth,
-- we must allow 'anon' (public) access to upload images.

-- 1. Ensure Bucket Exists
INSERT INTO storage.buckets (id, name, public)
VALUES ('profiles', 'profiles', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- 2. Drop Restrictive Policies
DROP POLICY IF EXISTS "Authenticated Upload Profiles" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Update Profiles" ON storage.objects;
DROP POLICY IF EXISTS "Public Access Profiles" ON storage.objects;
DROP POLICY IF EXISTS "Public Upload Profiles" ON storage.objects;
DROP POLICY IF EXISTS "Public Update Profiles" ON storage.objects;

-- 3. Create Open Policies (Allow Anon Uploads)
CREATE POLICY "Public Access Profiles" ON storage.objects FOR SELECT USING (bucket_id = 'profiles');
CREATE POLICY "Public Upload Profiles" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'profiles');
CREATE POLICY "Public Update Profiles" ON storage.objects FOR UPDATE USING (bucket_id = 'profiles');

NOTIFY pgrst, 'reload config';`;

const v10UpdateSQL = `-- Update V10: Provider Notifications System
-- 1. Create Notifications Table
CREATE TABLE IF NOT EXISTS public.provider_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  provider_id bigint NULL,
  message text NULL,
  is_read boolean DEFAULT false,
  type text DEFAULT 'BOOKING',
  CONSTRAINT provider_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT provider_notifications_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- 2. Enable RLS
ALTER TABLE public.provider_notifications ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies (Public Access for demo purposes to allow bot insertion and provider reading)
CREATE POLICY "Public Access ProviderNotifications" ON public.provider_notifications FOR ALL USING (true) WITH CHECK (true);

-- 4. Refresh Cache
NOTIFY pgrst, 'reload config';`;

const sampleDataSQL = `-- Sample Providers
INSERT INTO public.providers (name, service_type, location, username, password, phone, is_active, subscription_end_date, latitude, longitude) VALUES
('Dr. Fatima Alami', 'General Doctor', 'Ibn Batouta Clinic, Tangier', 'fatima.alami', 'pass123', '0611223344', true, now() + interval '30 days', 35.7721, -5.8025),
('Yassine Electric', 'Electrician', 'Mesnana, Tangier', 'yassine.electric', 'pass123', '0655667788', true, now() + interval '30 days', 35.7644, -5.8210),
('Plomberie Express', 'Plumber', 'City Center, Tangier', 'plomberie.express', 'pass123', '0699887766', true, now() + interval '30 days', 35.7750, -5.8000),
('Dr. Karim Bennani', 'Dentist', 'Malabata, Tangier', 'karim.bennani', 'pass123', '0644332211', true, now() + interval '30 days', 35.7780, -5.7900)
ON CONFLICT (username) DO NOTHING;`;

const reloadSchemaSQL = `NOTIFY pgrst, 'reload config';`;

const fixRLSPoliciesSQL = `-- Enable RLS
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.providers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.follow_ups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scan_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provider_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provider_notifications ENABLE ROW LEVEL SECURITY;

-- DROP EXISTING POLICIES
DROP POLICY IF EXISTS "Public Access Clients" ON public.clients;
DROP POLICY IF EXISTS "Public Access Providers" ON public.providers;
DROP POLICY IF EXISTS "Public Access Appointments" ON public.appointments;
DROP POLICY IF EXISTS "Public Access FollowUps" ON public.follow_ups;
DROP POLICY IF EXISTS "Public Access Announcements" ON public.announcements;
DROP POLICY IF EXISTS "Public Access Follows" ON public.follows;
DROP POLICY IF EXISTS "Public Access ScanHistory" ON public.scan_history;
DROP POLICY IF EXISTS "Public Access ProviderServices" ON public.provider_services;
DROP POLICY IF EXISTS "Public Access ProviderNotifications" ON public.provider_notifications;

-- CREATE PERMISSIVE POLICIES
CREATE POLICY "Public Access Clients" ON public.clients FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Providers" ON public.providers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Appointments" ON public.appointments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access FollowUps" ON public.follow_ups FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Announcements" ON public.announcements FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Follows" ON public.follows FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access ScanHistory" ON public.scan_history FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access ProviderServices" ON public.provider_services FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access ProviderNotifications" ON public.provider_notifications FOR ALL USING (true) WITH CHECK (true);

NOTIFY pgrst, 'reload config';`;

  if (!isOpen) return null;

  return (
    <>
      <div className="fixed inset-0 bg-black/60 z-40" onClick={onClose}></div>
      <div className="fixed top-0 right-0 rtl:left-0 rtl:right-auto h-full w-full max-w-2xl bg-gray-100 dark:bg-gray-800 shadow-xl z-50 transform transition-transform duration-300 ease-in-out" style={{ transform: isOpen ? 'translateX(0)' : 'translateX(100%)' }}>
        <div className="p-4 flex justify-between items-center border-b border-gray-200 dark:border-gray-700 sticky top-0 bg-gray-100 dark:bg-gray-800 z-10">
          <h3 className="text-xl font-bold text-dark dark:text-light flex items-center gap-2">
            <Database /> {t('databaseSetupTitle')}
          </h3>
          <button onClick={onClose} className="p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-600">
            <X size={24} className="text-dark dark:text-light" />
          </button>
        </div>
        <div className="p-6 h-[calc(100vh-65px)] overflow-y-auto">
          <p className="mb-6 text-gray-700 dark:text-gray-300">{t('databaseSetupDesc')}</p>
          
          {/* V10 Update Block */}
          <div className="mb-8 p-4 border-l-4 border-teal-500 bg-teal-50 dark:bg-teal-900/20 rounded-r-lg shadow-lg animate-fade-in">
             <h3 className="text-xl font-bold text-teal-600 dark:text-teal-400 flex items-center gap-2 mb-4">
                <Bell /> {t('v10UpdateTitle')}
             </h3>
             <CodeBlock title={t('v10UpdateTitle')} code={v10UpdateSQL.trim()} />
          </div>

          {/* V9 Update Block */}
          <div className="mb-8 p-4 border-l-4 border-indigo-500 bg-indigo-50 dark:bg-indigo-900/20 rounded-r-lg shadow-lg animate-fade-in">
             <h3 className="text-xl font-bold text-indigo-600 dark:text-indigo-400 flex items-center gap-2 mb-4">
                <Unlock /> {t('v9UpdateTitle')}
             </h3>
             <CodeBlock title={t('v9UpdateTitle')} code={v9UpdateSQL.trim()} />
          </div>

          {/* V8 Emergency Fix Block */}
          <div className="mb-8 p-4 border-l-4 border-red-500 bg-red-50 dark:bg-red-900/20 rounded-r-lg">
             <h3 className="text-xl font-bold text-red-600 dark:text-red-400 flex items-center gap-2 mb-4">
                <ShieldAlert /> {t('v8UpdateTitle')}
             </h3>
             <CodeBlock title={t('v8UpdateTitle')} code={v8UpdateSQL.trim()} />
          </div>
          
          <div className="mb-8 p-4 border-l-4 border-red-500 bg-red-50 dark:bg-red-900/20 rounded-r-lg">
             <h3 className="text-xl font-bold text-red-600 dark:text-red-400 flex items-center gap-2 mb-4">
                <AlertTriangle /> {t('troubleshootingTitle')}
             </h3>
             <p className="mb-4 text-gray-800 dark:text-gray-200 font-semibold">{t('troubleshootingDesc')}</p>
             <div className="relative bg-gray-800 rounded-md p-3 font-mono text-xs text-green-400">
                 <pre>{reloadSchemaSQL}</pre>
             </div>
             <div className="mt-4 relative bg-gray-800 rounded-md p-3 font-mono text-xs text-blue-400">
                 <pre>{fixRLSPoliciesSQL}</pre>
             </div>
          </div>

          <CodeBlock title={t('completeSQLScript')} code={completeSQL.trim()} />
        </div>
      </div>
    </>
  );
};

export default DatabaseSetup;